dist: trusty
sudo: required

language: node_js
node_js:
  - "7"

services:
  - mongodb

before_install:
  - npm install -g nodemon

install:
  - npm install

before_script:
  - mongod
  - sleep 15

script:
  - npm start

after_script:
  - mongod --shutdown
